upload:
#  Nginx 文件上传路径为：E:/nginx/local/upload/
  url: http://127.0.0.1:8089/
#  最终文件的访问路径：http://127.0.0.1:8089/53CE765D2770486AB51EDFF525AC53E8bj.png
  path: E:/nginx/local/upload/
# 端口号
server:
  port: 8880
  servlet:
    context-path: /api
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hairorder?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
#    redis配置

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 500
SSM:
  appid: xx
  appkey: xxx
  smsSign: "xxx"
  templateId: xx
