# 端口号
server:
  port: 8880
  servlet:
    context-path: /api
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haircut?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
#    redis配置
#  redis:
#    host: 127.0.0.1
#    port: 6379